# Generated by Django 4.1.3 on 2022-11-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('cover_image', models.ImageField(upload_to='uploads/')),
                ('content', models.CharField(max_length=100000000)),
            ],
        ),
    ]
